# Generated by Django 2.1.2 on 2018-11-07 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('', 'Seleccione una marca'), ('Suzuki', 'Suzuki'), ('Hiunday', 'Hiunday')], default='', max_length=50)),
                ('modelo', models.CharField(max_length=25, verbose_name='Modelo')),
                ('puertas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Cantidad de puertas')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año')),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
